[package]
name = "edr_solidity"
version = "0.2.0-dev"
edition = "2021"

[dependencies]
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.89" }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
alloy-json-abi = "0.5.2"
thiserror = { version = "1.0.38", default-features = false }
versions = "6.0.0"
