name: PR approved Slack notification
on:
  pull_request_review:
    types: [submitted]
jobs:
  approved:
    uses: NomicFoundation/github-actions-workflows/.github/workflows/review-approved-slack-notification.yml@main
    secrets: inherit
